name: Deploy
on:
  push:
    branches:
      - pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build docs
        run: mkdocs build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deploy.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy page
        id: deploy
        uses: actions/deploy-pages@v4
